<?php
$dbip='localhost';
$dbuser='root';
$dbpass='123456';
$dbname='demo01';
$con=mysqli_connect($dbip,$dbuser,$dbpass,$dbname);
if(!$con){
    die("连接失败:".mysqli_connect_error());
}else{
    mysqli_set_charset($con,'utf8');
}
?>